# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DB_DATABASE: tp_project_movies_db
  DB_USER: root
  DB_PASSWORD: 757020Key

jobs:  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        export PYTHONPATH=src
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        ${{ env.DB_PASSWORD }} | sudo mysql_secure_installation
        sudo mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} << MYSQL
        create user '${{ env.DB_USER }}'@'localhost' identified by '${{ env.DB_PASSWORD }}';
        create database ${{ env.DB_DATABASE }};
        USE ${{ env.DB_DATABASE }};
        GRANT ALL ON ${{ env.DB_DATABASE }}.* TO '${{ env.DB_USER }}'@'localhost';
        SET GLOBAL log_bin_trust_function_creators = 1;
        MYSQL
    - name: Lint with flake8
      run: |
        export PYTHONPATH=src
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        export PYTHONPATH=src
        pytest
